<?php

namespace AppBundle\Repository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUsers($data) {

        $query = $this->createQueryBuilder('p')
                      ->where('p.nom = :data')
                      ->setParameter('data', $data)
                      ->getQuery();


        return $query->getQuery()->getResult();
    }
}
