# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    # Pour la redirection aprés l'authentification
    authentication.handler.login_success_handler:
        class:  AppBundle\Redirection\LoginSuccessHandler
        arguments:  ['@router', '@security.authorization_checker']


    #
    admin.user:
        class: AppBundle\Admin\AdminUser
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Employés }
        public: true


    admin.Projet:
        class: AppBundle\Admin\AdminProjet
        arguments: [~, AppBundle\Entity\Projet, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Projet }
        public: true

    admin.Client:
        class: AppBundle\Admin\AdminClient
        arguments: [~, AppBundle\Entity\Client, ~]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Client }
        public: true